export const FETCH_INTERVIEWERS_REQUEST = 'FETCH_INTERVIEWERS_REQUEST'
export const FETCH_INTERVIEWERS_SUCCESS = 'FETCH_INTERVIEWERS_SUCCESS'
export const FETCH_INTERVIEWERS_FAILURE = 'FETCH_INTERVIEWERS_FAILURE'