export const FETCH_INTERVIEWEES_REQUEST = 'FETCH_INTERVIEWEES_REQUEST'
export const FETCH_INTERVIEWEES_SUCCESS = 'FETCH_INTERVIEWEES_SUCCESS'
export const FETCH_INTERVIEWEES_FAILURE = 'FETCH_INTERVIEWEES_FAILURE'